# Generated by Django 4.2.2 on 2023-07-02 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(max_length=255, null=True)),
            ],
            options={
                'unique_together': {('name', 'city', 'county')},
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='core.organization')),
            ],
            options={
                'unique_together': {('type', 'route', 'organization')},
            },
        ),
    ]
